name: CI
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: 'ServiceNow DevOps Change'
    steps:
    - name: ServiceNow Change
      uses: ServiceNow/servicenow-devops-change@v3.0.0
      with:
        # Devops Integration Token
        devops-integration-token: "nucNnbAX7BLuwkPY8mTzQVFZGbwbwEmO"
        # ServiceNow Instance URL
        instance-url: "https://dev269477.service-now.com/"
        # Orchestration Tool Id
        tool-id: "e4ee4af5c32702102a5afb2ed40131ca"
        # GitHub Context
        context-github: ${{ toJSON(github) }}
        # Display Name of the Job
        job-name: 'ServiceNow DevOps Change'
        
